POST https://vikhub.dk/person/api/person/
Content-Type: application/json

{
  "fName": "vincent",
  "lName": "buchholz",
  "phone": "345522"

}

###

GET http://localhost:8080/devops_starter_war_exploded/api/person/1

###

GET https://vikhub.dk/person/api/person/all

###

PUT http://localhost:8080/devops_starter_war_exploded/api/person/2
Content-Type: application/json

{

  "lName": "Buchholz",
  "phone": "232334"

}

###

DELETE http://localhost:8080/devops_starter_war_exploded/api/person/6

###